name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build editor
        run: |
          npm install
          npm run build

      - name: Build documentation
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src
          recurse: true
          output_dir: ./dest/docs
          template: minami

      - name: Build documentation for the editor
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./editor/src
          recurse: true
          output_dir: ./dest/docs/editor
          template: minami

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dest
          CLEAN: true